#!/bin/bash

current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")

html_files=$(find "$current_dir" -maxdepth 1 -type f -name "*.html")

for html_file in $html_files; do
    file_name=$(basename "$html_file")
    parent_file_path="$parent_dir/$file_name"

    if [[ ! -e "$parent_file_path" ]]; then
        cp -u "$html_file" "$parent_dir"

